framework:
    cache:
        # Unique name of your app: used to compute stable namespaces for cache keys.
        prefix_seed: nowa_nadzieja/crm

        # Default cache adapter - Redis for better performance
        app: cache.adapter.redis
        default_redis_provider: '%env(REDIS_URL)%/0'

        # Additional cache pools for different purposes
        pools:
            # Cache for Doctrine queries (TTL: 1 hour)
            cache.doctrine:
                adapter: cache.adapter.redis
                provider: '%env(REDIS_URL)%/1'
                default_lifetime: 3600

            # Cache for statistics and dashboard data (TTL: 5 minutes)
            cache.statistics:
                adapter: cache.adapter.redis
                provider: '%env(REDIS_URL)%/2'
                default_lifetime: 300

            # Cache for user data and permissions (TTL: 10 minutes)
            cache.users:
                adapter: cache.adapter.redis
                provider: '%env(REDIS_URL)%/3'
                default_lifetime: 600

            # Cache for rendered templates (TTL: 1 hour)
            cache.templates:
                adapter: cache.adapter.redis
                provider: '%env(REDIS_URL)%/4'
                default_lifetime: 3600
