# See the configuration reference at https://symfony.com/bundles/SchebTwoFactorBundle/6.x/configuration.html
scheb_two_factor:
    security_tokens:
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
        - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken

    # Google Authenticator configuration
    google:
        enabled: true
        server_name: 'Nowa Nadzieja CRM'
        issuer: 'Nowa Nadzieja'
        template: 'security/2fa_form.html.twig'
