# config/packages/security.yaml
security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: login
                check_path: login
                default_target_path: /
                always_use_default_target_path: true
                username_parameter: email
                password_parameter: password
            two_factor:
                auth_form_path: 2fa_login
                check_path: 2fa_login_check
                prepare_on_login: true
                prepare_on_access_denied: true
            logout:
                path: logout
                target: login
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 week
                path: /
                secure: auto
                httponly: true
                samesite: strict
                always_remember_me: false
                remember_me_parameter: '_remember_me'

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/password-reset-request, roles: PUBLIC_ACCESS }
        - { path: ^/2fa/cancel, roles: PUBLIC_ACCESS }
        - { path: ^/2fa, roles: IS_AUTHENTICATED_2FA_IN_PROGRESS }
        - { path: ^/first-login, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/test/qr, roles: PUBLIC_ACCESS }
        - { path: ^/test-mail, roles: ROLE_ADMIN }
        - { path: ^/api/struktura, roles: PUBLIC_ACCESS }
        - { path: ^/api/kandydat, roles: PUBLIC_ACCESS }
        - { path: ^/api/mlodziezowka, roles: PUBLIC_ACCESS }
        - { path: ^/\.well-known/, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }

    role_hierarchy:
        # Role funkcyjne zarządu krajowego (dodatkowo do podstawowej roli użytkownika)
        ROLE_PREZES_PARTII: [ROLE_ZARZAD_KRAJOWY, ROLE_ADMIN]
        ROLE_WICEPREZES_PARTII: [ROLE_ZARZAD_KRAJOWY, ROLE_ADMIN]
        ROLE_SEKRETARZ_PARTII: [ROLE_ZARZAD_KRAJOWY, ROLE_ADMIN]
        ROLE_SKARBNIK_PARTII: [ROLE_ZARZAD_KRAJOWY, ROLE_ADMIN]
        ROLE_RZECZNIK_PRASOWY: [ROLE_ZARZAD_KRAJOWY, ROLE_ADMIN]

        # Role Rady Krajowej
        ROLE_PRZEWODNICZACY_RADY: [ROLE_RADA_KRAJOWA, ROLE_FUNKCYJNY]
        ROLE_ZASTEPCA_PRZEWODNICZACY_RADY: [ROLE_RADA_KRAJOWA, ROLE_FUNKCYJNY]

        # Role Komisji Rewizyjnej
        ROLE_PRZEWODNICZACY_KOMISJI_REW: [ROLE_KOMISJA_REWIZYJNA, ROLE_FUNKCYJNY]
        ROLE_WICEPRZEWODNICZACY_KOMISJI_REW: [ROLE_KOMISJA_REWIZYJNA, ROLE_FUNKCYJNY]
        ROLE_SEKRETARZ_KOMISJI_REW: [ROLE_KOMISJA_REWIZYJNA, ROLE_FUNKCYJNY]

        # Role funkcyjne zarządu regionu
        ROLE_PREZES_REGIONU: [ROLE_ZARZAD_REGIONU, ROLE_FUNKCYJNY]
        ROLE_SEKRETARZ_REGIONU: [ROLE_ZARZAD_REGIONU, ROLE_FUNKCYJNY]
        ROLE_SKARBNIK_REGIONU: [ROLE_ZARZAD_REGIONU, ROLE_FUNKCYJNY]

        # Role funkcyjne zarządu okręgu
        ROLE_PREZES_OKREGU: [ROLE_ZARZAD_OKREGU]
        ROLE_WICEPREZES_OKREGU: [ROLE_ZARZAD_OKREGU]
        ROLE_SEKRETARZ_OKREGU: [ROLE_ZARZAD_OKREGU]
        ROLE_SKARBNIK_OKREGU: [ROLE_ZARZAD_OKREGU]
        ROLE_PELNOMOCNIK_PRZYJMOWANIA: [ROLE_ZARZAD_OKREGU]
        ROLE_PO_PREZES_OKREGU: [ROLE_ZARZAD_OKREGU]

        # Role funkcyjne zarządu oddziału
        ROLE_PRZEWODNICZACY_ODDZIALU: [ROLE_ZARZAD_ODDZIALU]
        ROLE_ZASTEPCA_PRZEWODNICZACEGO_ODDZIALU: [ROLE_ZARZAD_ODDZIALU]
        ROLE_SEKRETARZ_ODDZIALU: [ROLE_ZARZAD_ODDZIALU]

        # Role struktur parlamentarnych
        ROLE_PRZEWODNICZACY_KLUBU: [ROLE_FUNKCYJNY]
        ROLE_PRZEWODNICZACY_DELEGACJI: [ROLE_FUNKCYJNY]

        # Role pełnomocników
        ROLE_PELNOMOCNIK_STRUKTUR: [ROLE_FUNKCYJNY]

        # Role tymczasowe dla zebrań oddziałów
        ROLE_OBSERWATOR_ZEBRANIA: [ROLE_CZLONEK_PARTII]          # tymczasowa rola obserwatora zebrania
        ROLE_PROTOKOLANT_ZEBRANIA: [ROLE_CZLONEK_PARTII]         # tymczasowa rola protokolanta zebrania
        ROLE_PROWADZACY_ZEBRANIA: [ROLE_CZLONEK_PARTII]          # tymczasowa rola prowadzącego zebrania

        # Hierarchie grupowe funkcyjnych
        ROLE_ZARZAD_KRAJOWY: [ROLE_FUNKCYJNY]
        ROLE_RADA_KRAJOWA: [ROLE_FUNKCYJNY]
        ROLE_KOMISJA_REWIZYJNA: [ROLE_FUNKCYJNY]
        ROLE_ZARZAD_REGIONU: [ROLE_FUNKCYJNY]
        ROLE_ZARZAD_OKREGU: [ROLE_FUNKCYJNY]
        ROLE_ZARZAD_ODDZIALU: [ROLE_FUNKCYJNY]
        ROLE_FUNKCYJNY: [ROLE_CZLONEK_PARTII]
        ROLE_ADMIN: [ROLE_USER]

        # Rola przekazu medialnego
        ROLE_PRZEKAZ: [ROLE_CZLONEK_PARTII]     # dostęp do wysyłania przekazów medialnych

        # Role podstawowe - każdy użytkownik ma jedną z tych ról jako podstawową
        ROLE_CZLONEK_PARTII: [ROLE_USER]        # członkowie partii
        ROLE_KANDYDAT_PARTII: [ROLE_USER]       # kandydaci na członków
        ROLE_DARCZYNCA: [ROLE_USER]             # darczyńcy
        ROLE_SYMPATYK: [ROLE_USER]              # sympatycy
        ROLE_BYLY_CZLONEK: [ROLE_USER]          # byli członkowie
