# Production security settings - updated for Symfony 7.3
security:
    firewalls:
        main:
            # CSRF protection
            form_login:
                enable_csrf: true
                csrf_parameter: _csrf_token
                csrf_token_id: authenticate
            
            # Stricter remember me settings for production
            remember_me:
                secure: true  # Force secure cookies
                httponly: true
                samesite: strict

# Additional security headers
framework:
    session:
        cookie_secure: true
        cookie_httponly: true
        cookie_samesite: strict