# Production security settings
security:
    firewalls:
        main:
            # Force HTTPS in production
            requires_channel: https
            
            # Session fixation protection
            session_fixation_strategy: migrate
            
            # CSRF protection
            form_login:
                enable_csrf: true
                csrf_parameter: _csrf_token
                csrf_token_id: authenticate
            
            # Stricter remember me settings for production
            remember_me:
                secure: true  # Force secure cookies
                httponly: true
                samesite: strict
                token_provider: 'Symfony\Bridge\Doctrine\Security\RememberMe\DoctrineTokenProvider'

# Additional security headers
framework:
    session:
        cookie_secure: true
        cookie_httponly: true
        cookie_samesite: strict