controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# Handle Chrome DevTools requests to prevent 404 errors
chrome_devtools:
    path: /.well-known/appspecific/com.chrome.devtools.json
    methods: [GET]
    controller: App\Controller\DevToolsController::chromeDevTools
